name: CI

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['**']

jobs:
  secret-scan:
    uses: zerotheft-org/zt-plat-github-workflows/.github/workflows/reusable-secret-scan.yml@v1.1.3
    permissions:
      actions: read
      contents: read
      security-events: write

  sast-scan:
    uses: zerotheft-org/zt-plat-github-workflows/.github/workflows/reusable-sast-scan.yml@v1.1.3
    permissions:
      actions: read
      contents: read
      security-events: write

  dependency-scan:
    uses: zerotheft-org/zt-plat-github-workflows/.github/workflows/reusable-dependency-scan.yml@v1.1.3
    permissions:
      actions: read
      contents: read
      security-events: write

  backend-ci:
    needs: [secret-scan, sast-scan, dependency-scan]
    uses: zerotheft-org/zt-plat-github-workflows/.github/workflows/reusable-backend-ci.yml@v1.1.3
    with:
      python-version: "3.12"

  docker-build-push:
    needs: [backend-ci]
    uses: zerotheft-org/zt-plat-github-workflows/.github/workflows/reusable-docker-build-push.yml@v1.1.3
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      service_name: zt/notification-service
      dockerfile_path: Dockerfile
      context: .
      codeartifact_domain: zerotheft
      codeartifact_repo: zerotheft-python
      codeartifact_owner: "744561091152"
    secrets:
      aws_role_arn: ${{ secrets.AWS_ECR_PUSH_ROLE_ARN }}

  security-reporting:
    needs: [secret-scan, sast-scan, dependency-scan]
    if: always()
    uses: zerotheft-org/zt-plat-github-workflows/.github/workflows/reusable-defectdojo-upload.yml@v1.1.3
    permissions:
      contents: read
    secrets:
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
